<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>thriving.softwood</groupId>
        <artifactId>spring-boot-01</artifactId>
        <version>0.0.5-SNAPSHOT</version>
    </parent>
    <artifactId>kaishi</artifactId>
    <name>kaishi</name>
    <description>凯诗外挂系统</description>
    <properties>
        <java.version>${jdk.version}</java.version>
    </properties>

    <dependencies>
        <!--00.项目内依赖 begin-->
        <dependency>
            <groupId>thriving.softwood.common</groupId> <!-- 注意这里是 common -->
            <artifactId>common-auth</artifactId>
        </dependency>
        <dependency>
            <groupId>thriving.softwood.common</groupId>
            <artifactId>common-file</artifactId>
        </dependency>
        <!-- ✨ 引入刚建好的数据库底座 -->
        <dependency>
            <groupId>thriving.softwood.common</groupId>
            <artifactId>common-database</artifactId>
        </dependency>
        <!-- 引入消息中心 -->
        <dependency>
            <groupId>thriving.softwood.common</groupId>
            <artifactId>common-message</artifactId>
        </dependency>
        <!--00.项目内依赖 end-->

        <!--01.日志实现依赖 begin-->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-layout-template-json</artifactId>
        </dependency>
        <!--01.日志实现依赖 end-->

        <!--02.开发辅助依赖 begin-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- ✨ 显式指定具体使用的数据库驱动 -->
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.connector.version}</version>
            <optional>true</optional>
        </dependency>
        <!--02.开发辅助依赖 end-->
    </dependencies>


    <profiles>

        <profile>
            <id>prod-build</id>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <!-- 🚀 核心动作：打包时剔除所有的 yml 配置文件 -->
                        <excludes>
                            <!-- 剔除 config 文件夹下所有的 yml -->
                            <exclude>config/**/*.yml</exclude>
                            <!-- 如果根目录下还有，也可以一起剔除 -->
                            <exclude>application*.yml</exclude>
                        </excludes>
                    </resource>
                    <resource>
                        <directory>src/main/java</directory>
                        <includes>
                            <include>thriving/softwood/**/mapper/**/*.xml</include>
                        </includes>
                        <filtering>false</filtering>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
        <finalName>${project.artifactId}-plus</finalName>
    </build>

</project>
