<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>thriving.softwood</groupId>
        <artifactId>common</artifactId>
        <version>0.0.4-SNAPSHOT</version>
    </parent>
    <artifactId>common-auth</artifactId>
    <groupId>thriving.softwood.common</groupId>
    <name>common-auth</name>
    <description>身份管理中台：处理用户、角色、部门、权限、数据规则的 CRUD 及提供鉴权数据源</description>
    <properties>
        <java.version>${jdk.version}</java.version>
    </properties>

    <dependencies>
        <!--00.项目内依赖 begin-->
        <!-- ✨ 引入刚建好的数据库底座 -->
        <dependency>
            <groupId>thriving.softwood.common</groupId>
            <artifactId>common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>thriving.softwood.common</groupId>
            <artifactId>common-database</artifactId>
        </dependency>
        <!--00.项目内依赖 end-->
    </dependencies>


    <build>
    </build>

</project>
