# 查看配置类加载详情
#debug: true

spring:
  application:
    name: kaishi
  messages:
    basename: i18n.kaishi
  profiles:
    active: dev
  web:
    # 默认就是 accept-header
    locale-resolver: accept_header
    # 当 locale-resolver: fixed 被配置时下方 locale 设置才生效; en_US 是 locale 的默认值,Accept-Language 为空时才生效
    locale: en_US
  #    active: prod
  #  main:
  #    laz y-initialization: true

  # 🔥 核心魔法：按模块组装所有拆分出来的配置文件
  config:
    import:
      - application-db.yml
      - application-mybatis.yml
      - application-async.yml
      - application-observability.yml
      - application-security.yml