server:
  port: 6160
  servlet:
    context-path: /dev

logging:
  # log4j2-dev.xml 配置文件提供骨架
  config: classpath:config/logging/log4j2-dev.xml
  # application.yml 进行精细控制
  level:
    thriving:
      softwood: trace

async:
  vt:
    thread-name-prefix: vt-exec-
    concurrency-limit: 300
  pt:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 500
    thread-name-prefix: pt-exec
    rejected-exec-handler-type: AbortPolicy

security:
  sm4:

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: meta-thriving
        login password: ENC(aa3411511790ce0c0c9e1ecc81f8b9f8)
    #        login password: Wancc16#
    dynamic:
      druid:
        initial-size: 1
        max-active: 3000
        # filters: stat,wall
        wall:
          none-base-statement-allow: true
        stat:
          merge-sql: true
          log-slow-sql: false
          slow-sql-millis: 20000
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          username: postgres
          password: ENC(aa3411511790ce0c0c9e1ecc81f8b9f8)
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/splash-inkflow
          druid:
            initial-size: 1
        novel:
          type: com.alibaba.druid.pool.DruidDataSource
          username: postgres
          password: ENC(aa3411511790ce0c0c9e1ecc81f8b9f8)
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/weaving-stars
          druid:
            initial-size: 1
        material:
          type: com.alibaba.druid.pool.DruidDataSource
          username: postgres
          password: ENC(aa3411511790ce0c0c9e1ecc81f8b9f8)
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/source-material
          druid:
            initial-size: 1
        embedding:
          type: com.alibaba.druid.pool.DruidDataSource
          username: postgres
          password: ENC(aa3411511790ce0c0c9e1ecc81f8b9f8)
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/embedding-libraries
          druid:
            initial-size: 1

  sql:
    init:
      encoding: utf-8

# 🚀 MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/thriving/softwood/**/mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    # 开发环境打印 SQL (生产环境请务必关闭，或使用 p6spy)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: thriving.softwood.**.database.pojo